/****************************************************************************************************************************************************
 * * IMPORTS
 ****************************************************************************************************************************************************/
import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import SideBar from '@/components/containers/SideBar';
import { useTranslations } from 'next-intl';
import BurgerMenu from '@/components/BurgerMenu';
import ChangePages from '@/components/ChangePages';
import React from 'react';

/****************************************************************************************************************************************************
 * * TYPES - INTERFACES - CLASES
 ****************************************************************************************************************************************************/
type RootLayoutProps = {
  children: React.ReactNode;
  params: { locale: string };
};

/****************************************************************************************************************************************************
 * * DECLARATIONS
 ****************************************************************************************************************************************************/
// const inter = Inter({ subsets: ['latin'] });

/****************************************************************************************************************************************************
 * * FUNCTIONS
 ****************************************************************************************************************************************************/
const RootLayout: React.FC<RootLayoutProps> = ({
  children,
  params: { locale },
}) => {
  const t = useTranslations('Portfolio');
  const middleTexts = {
    work: t('side.work'),
    download: t('side.downloadButton'),
  };
  return (
    <>
      <html lang={locale}>
        <link
          rel='stylesheet'
          type='text/css'
          href='https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css'
        />
        <body className='w-screen text-sm md:text-lg h-screen grid grid-cols-10 grid-rows-5 overflow-hidden bg-my-black'>
          <BurgerMenu />
          <SideBar middleTexts={middleTexts} locale={locale} />
          <main className='col-start-1 col-end-11 row-start-1 row-end-6 w-full h-full lg:col-start-4 lg:col-end-11'>
            <ChangePages locale={locale} />
            {children}
          </main>
        </body>
      </html>
    </>
  );
};

/****************************************************************************************************************************************************
 * * EXPORTS
 ****************************************************************************************************************************************************/
export const metadata: Metadata = {
  title: 'Arsian',
  description: 'Generated by create next app',
};

export default RootLayout;
